language: node_js
node_js: "0.12"
script: npm run travisci
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "A8MPbM45k5a+ow8j7WZ/2xQ6A0YBI57VJm4f/3+MuG3pud10URWTnsS/XI4mYoDQLACkXQQxbrpBfmq8L4uHbHi5RqnyyGo6Ug2lZ1bV1phoH2GQU9W3OnX4r33VypLX8gouNdOFhiobn3l6tbnQm4CFrZkE3ItWa7ysjo7S+FgJcJx6IufnMS0IZqUe1vrKcs0gWp1VAcri/CJeyVQJBnH2EO4uxd0pX87B3Hp9HdNmt7hvPQeTOD759RGxk4vbM2Sw4Sk21u0Og7Wlr+H/33JtA/GqjePwPvTUfvgp+7dDd57f1txCtfYVnVmgomfFKKsgiAvGmNbzqELR3DJlKYh4hph27asmKb0qaajSCKFrIgGCdwzYBOj6Ln0wCwevGB1lqkmb0eCJrAOcKc7yF+oKkwllm2WKgPbsHMeVWabnqLVqaLfG+FnBzy5BaiukvFUQBd3hBGFdWQHJrkU5U3QdHhdmVyx44vmi8pbg00YwOdRbOfZfio9Nlik6r8cFXezHyEIx6E0zequaAmI9j0zPdhHFzk7RPQ889ksLfBRhmZn0tITOGIh+apYrpqk1rjQkO2uigXnyFpzr7izFYoDboJVgIjSsOagy1UAvEVFL0rEkiC+z9LUK8h/JUj3C8Y5U9NvCyugTwlAdg645wxhMxNKPCqbKB5P6l7etaQ4="
